// series
export const TVDB_LOGIN_START = 'TVDB_LOGIN_START';
export const TVDB_LOGIN_SUCCESS = 'TVDB_LOGIN_SUCCESS';
export const TVDB_FAIL = 'TVDB_FAIL';
//export const TVDB_LOGOUT = 'TVDB_LOGOUT';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';
export const DELETE_ORDER = 'DELETE_ORDER';

// auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';